#ifndef AUDUINO_HWDEFINES_h
#define AUDUINO_HWDEFINES_h

#define FALSE 0
#define TRUE 1

#define NUMBER_OF_KNOBS 5

#define NUMBER_OF_BUTTONS 7 
#define NUMBER_OF_DIODS 7  

#define BUTTON_EDIT_MODE_INDEX 0
#define BUTTON_LFO_INDEX 1
#define BUTTON_ADSR_INDEX 2
#define BUTTON_INSTRUMENT_1_INDEX 3
#define BUTTON_INSTRUMENT_2_INDEX 4
#define BUTTON_INSTRUMENT_3_INDEX 5
#define BUTTON_INSTRUMENT_4_INDEX 6

#define DIOD_EDIT_MODE_INDEX 0
#define DIOD_LFO_INDEX 1
#define DIOD_ADSR_INDEX 2
#define DIOD_INSTRUMENT_1_INDEX 3
#define DIOD_INSTRUMENT_2_INDEX 4
#define DIOD_INSTRUMENT_3_INDEX 5
#define DIOD_INSTRUMENT_4_INDEX 6

#define BUTTON_EDIT_MODE_PIN 11    
#define BUTTON_LFO_PIN 9
#define BUTTON_ADSR_PIN 10
#define BUTTON_INSTRUMENT_1_PIN 2
#define BUTTON_INSTRUMENT_2_PIN 4 
#define BUTTON_INSTRUMENT_3_PIN 8
#define BUTTON_INSTRUMENT_4_PIN 7

#define DIOD_EDIT_MODE_PIN  11
#define DIOD_LFO_PIN 9
#define DIOD_ADSR_PIN 10 
#define DIOD_INSTRUMENT_1_PIN 2
#define DIOD_INSTRUMENT_2_PIN 4 
#define DIOD_INSTRUMENT_3_PIN 8
#define DIOD_INSTRUMENT_4_PIN 7

/* Knob definitions */ 

#define KNOB_TOLERANCE 10
#define KNOB_FREEZE_DISTANCE 128

#define KNOB_1_PIN 3 
#define KNOB_2_PIN 2 
#define KNOB_3_PIN 0 
#define KNOB_4_PIN 1 
#define KNOB_5_PIN 4 

#define KNOB_1_INDEX 0
#define KNOB_2_INDEX 1
#define KNOB_3_INDEX 2
#define KNOB_4_INDEX 3
#define KNOB_5_INDEX 4

#define KNOB_ADSR_A_INDEX 4 
#define KNOB_ADSR_D_INDEX 0
#define KNOB_ADSR_S_INDEX 1
#define KNOB_ADSR_R_INDEX 3
#define KNOB_ADSR_DEST_INDEX 2

#define KNOB_LFO_RATE_INDEX 4 
#define KNOB_LFO_SMOOTH_INDEX 0
#define KNOB_LFO_AMOUT_INDEX 1
#define KNOB_LFO_SHAPE_INDEX 3
#define KNOB_LFO_DEST_INDEX 2

#define KNOB_SYNTH_PITCH_INDEX 4
#define KNOB_SYNTH_GD1_INDEX 2
#define KNOB_SYNTH_GF1_INDEX 3
#define KNOB_SYNTH_GF2_INDEX 1
#define KNOB_SYNTH_GD2_INDEX 0

#define RADIO_NO_CONNECTION 255

#define RELEASE_BUTTON_BUFFER 10

#endif









